export const generateTeamName = () => {
    const nouns = [
        "cameras",
        "playing cards",
        "vases",
        "flowers",
        "twisters",
        "ice cubes",
        "slippers",
        "air fresheners",
        "shoes",
        "leg warmers",
        "plastic forks",
        "sofas",
        "thermometers",
        "books",
        "screws",
        "flags",
        "toe rings",
        "boom boxes",
        "buttons",
        "bucks",
        "shirts",
        "packing peanuts",
        "drill press",
        "toothpastes",
        "seat belts",
        "greeting cards",
        "hair brush",
        "keyboards",
        "soda cans",
        "paint brushes",
        "towels",
        "threads",
        "pianoes",
        "socks",
        "bananas",
        "credit cards",
        "computers",
        "chalk",
        "rusty nails",
        "washing machines",
        "bracelets",
        "nail files",
        "shovels",
        "wagons",
        "blouses",
        "sponges",
        "trees",
        "mouse pads",
        "tables",
        "chocolates",
        "cups",
        "doors",
        "sailboats",
        "cinder blocks",
        "helmets",
        "lamp shades",
        "street lights",
        "blankets",
        "soaps",
        "wallets",
        "chairs",
        "dolls",
        "rubber bands",
        "lip gloss",
        "zippers",
        "clay pots",
        "tooth picks",
        "apples",
        "canvas",
        "stockings",
        "headphones",
        "bowls",
        "carrots",
        "bottle caps",
        "watches",
        "lamps",
        "pens",
        "sketch pads",
        "beds",
        "plates",
        "mops",
        "glass",
        "shoe laces",
        "chargers",
        "toothbrushs",
        "couches",
        "sun glasses",
        "pillows",
        "toilets",
        "outlets",
        "perfumes",
        "cookie jars",
        "thermostats",
        "tire swings",
        "scotch tape",
        "purses",
        "lotions",
        "bows",
        "glow sticks",
        "pencils",
        "nail clippers",
        "water bottles",
        "video games",
        "CDs",
        "grid papers",
        "bags",
        "foods",
        "rubber ducks",
        "beef",
        "candles",
        "bookmarks",
        "cell phones",
        "key chains",
        "drawers",
        "sand papers",
        "checkbooks",
        "radios",
        "mirrors",
        "candy wrappers",
        "puddles",
        "monitors",
        "remotes",
        "pants",
        "shawls",
        "corks",
        "face wash",
        "brocolli",
        "speakers",
        "keys",
        "fake flowers",
        "desks",
        "controllers",
        "white outs",
        "springs",
        "glasses",
        "magnets",
        "shampoos",
        "floors",
        "tweezers",
        "laces",
        "rugs",
        "rings",
        "papers",
        "tissue boxes",
        "needles",
        "pool sticks",
        "phones",
        "bottles",
        "sticky notes",
        "ipods",
        "teddies",
        "fridges",
        "spoons",
        "milk",
        "cats",
        "soy sauce packets",
        "newspapers",
        "clamps",
        "hair ties",
        "knives",
        "clothes",
        "tvs",
        "deodorants",
        "picture frames",
        "trucks",
        "breads",
        "televisions",
        "sandals",
        "houses",
        "clocks",
        "coasters",
        "windows",
        "hangers",
        "tomatos",
        "cars",
        "erasers",
        "balloons",
        "model cars",
        "boxes",
        "stop signs",
        "starfish",
        "finch",
        "fish",
        "silver foxes",
        "pronghorns",
        "dung beetles",
        "chipmunks",
        "highland cows",
        "muskrats",
        "bunnies",
        "mynah birds",
        "polar bears",
        "pumas",
        "tigers",
        "bisons",
        "antelopes",
        "oxen",
        "oryx",
        "aardvarks",
        "turtles",
        "pigs",
        "goats",
        "walrus",
        "thorny devils",
        "hippopotamuses",
        "whales",
        "guinea pigs",
        "parrots",
        "zebras",
        "vicunas",
        "elephants",
        "snakes",
        "mares",
        "porcupines",
        "horses",
        "otters",
        "lizards",
        "puppies",
        "mice",
        "koalas",
        "deers",
        "waterbucks",
        "rats",
        "cats",
        "cows",
        "springboks",
        "anteaters",
        "iguanas",
        "giraffes",
        "hogs",
        "yaks",
        "gila monsters",
        "gorillas",
        "ocelots",
        "crows",
        "meerkats",
        "bumble bees",
        "hartebeests",
        "steer",
        "bulls",
        "chameleons",
        "sloths",
        "sheep",
        "ibex",
        "skunks",
        "cougars",
        "lynx",
        "marmosets",
        "mandrills",
        "alligators",
        "dormice",
        "reindeers",
        "dugongs",
        "chamois",
        "newts",
        "gazelles",
        "elands",
        "fawns",
        "quaggas",
        "mules",
        "hedgehogs",
        "blue crabs",
        "coyotes",
        "wolves",
        "lions",
        "llamas",
        "prairie dogs",
        "roosters",
        "seals",
        "kangaroos",
        "wildcats",
        "rhinoceros",
        "basilisks",
        "badgers",
        "does",
        "hares",
        "chinchillas",
        "pandas",
        "dromedarys",
        "lambs",
    ];
    const adverbs = [
        "abnormally",
        "absentmindedly",
        "accidentally",
        "actually",
        "adventurously",
        "afterwards",
        "almost",
        "always",
        "annually",
        "anxiously",
        "arrogantly",
        "awkwardly",
        "bashfully",
        "beautifully",
        "bitterly",
        "bleakly",
        "blindly",
        "blissfully",
        "boastfully",
        "boldly",
        "bravely",
        "briefly",
        "brightly",
        "briskly",
        "broadly",
        "busily",
        "calmly",
        "carefully",
        "carelessly",
        "cautiously",
        "certainly",
        "cheerfully",
        "clearly",
        "cleverly",
        "closely",
        "coaxingly",
        "colorfully",
        "commonly",
        "continually",
        "coolly",
        "correctly",
        "courageously",
        "crossly",
        "cruelly",
        "curiously",
        "daily",
        "daintily",
        "dearly",
        "deceivingly",
        "deeply",
        "defiantly",
        "deliberately",
        "delightfully",
        "diligently",
        "dimly",
        "doubtfully",
        "dreamily",
        "easily",
        "elegantly",
        "energetically",
        "enormously",
        "enthusiastically",
        "equally",
        "especially",
        "even",
        "evenly",
        "eventually",
        "exactly",
        "excitedly",
        "extremely",
        "fairly",
        "faithfully",
        "famously",
        "far",
        "fast",
        "fatally",
        "ferociously",
        "fervently",
        "fiercely",
        "fondly",
        "foolishly",
        "fortunately",
        "frankly",
        "frantically",
        "freely",
        "frenetically",
        "frightfully",
        "fully",
        "furiously",
        "generally",
        "generously",
        "gently",
        "gladly",
        "gleefully",
        "gracefully",
        "gratefully",
        "greatly",
        "greedily",
        "happily",
        "hastily",
        "healthily",
        "heavily",
        "helpfully",
        "helplessly",
        "highly",
        "honestly ",
        "hourly",
        "hungrily",
        "immediately",
        "innocently",
        "inquisitively",
        "instantly",
        "intensely",
        "intently",
        "interestingly",
        "inwardly",
        "irritably",
        "jaggedly",
        "jealously",
        "jovially",
        "joyfully",
        "joyously",
        "jubilantly",
        "judgmentally",
        "justly",
        "keenly",
        "kiddingly",
        "kindheartedly",
        "kindly",
        "knavishly",
        "knowingly",
        "knowledgeably",
        "kookily",
        "lazily",
        "les",
        "lightly",
        "likely",
        "limply",
        "lively",
        "loftily",
        "longingly",
        "loosely",
        "loudly",
        "lovingly",
        "loyally",
        "madly",
        "majestically",
        "meaningfully",
        "mechanically",
        "merrily",
        "miserably",
        "mockingly",
        "monthly",
        "more",
        "mortally",
        "mostly",
        "mysteriously",
        "naturally",
        "hopelessly",
        "hourly",
        "hungrily",
        "nearly",
        "neatly",
        "nervously",
        "never",
        "nicely",
        "noisily",
        "not",
        "obediently",
        "obnoxiously",
        "oddly",
        "offensively",
        "officially",
        "often",
        "only",
        "openly",
        "optimistically",
        "overconfidently",
        "painfully",
        "partially",
        "patiently",
        "perfectly",
        "physically",
        "playfully",
        "politely",
        "poorly",
        "positively",
        "potentially",
        "powerfully",
        "promptly",
        "properly",
        "punctually",
        "quaintly",
        "queasily",
        "queerly",
        "questionably",
        "quicker",
        "quickly",
        "quietly",
        "quirkily",
        "quizzically",
        "randomly",
        "rapidly",
        "rarely",
        "readily",
        "really",
        "reassuringly",
        "recklessly",
        "regularly",
        "reluctantly",
        "repeatedly",
        "reproachfully",
        "restfully",
        "righteously",
        "rightfully",
        "rigidly",
        "roughly",
        "rudely",
        "safely",
        "scarcely",
        "scarily",
        "searchingly",
        "sedately",
        "seemingly",
        "seldom",
        "selfishly",
        "separately",
        "seriously",
        "shakily",
        "sharply",
        "sheepishly",
        "shrilly",
        "shyly",
        "silently",
        "sleepily",
        "slowly",
        "smoothly",
        "softly",
        "solemnly",
        "solidly",
        "sometimes",
        "soon",
        "speedily",
        "stealthily",
        "sternly",
        "strictly",
        "successfully",
        "suddenly",
        "supposedly",
        "surprisingly",
        "suspiciously",
        "sweetly",
        "swiftly",
        "sympathetically",
        "tenderly",
        "tensely",
        "terribly",
        "thankfully",
        "thoroughly",
        "thoughtfully",
        "tightly",
        "tomorrow",
        "too",
        "tremendously",
        "triumphantly",
        "truly",
        "truthfully",
        "ultimately",
        "unabashedly",
        "unaccountably",
        "unbearably",
        "unethically",
        "unexpectedly",
        "unfortunately",
        "unimpressively",
        "unnaturally",
        "unnecessarily",
        "upbeat",
        "upright",
        "upside-down",
        "upward",
        "urgently",
        "usefully",
        "uselessly",
        "usually",
        "utterly",
        "vacantly",
        "vaguely",
        "vainly",
        "valiantly",
        "vastly",
        "verbally",
        "very",
        "viciously",
        "victoriously",
        "violently",
        "vivaciously",
        "voluntarily",
        "warmly",
        "weakly",
        "wearily",
        "well",
        "wetly",
        "wholly",
        "wildly",
        "willfully",
        "wisely",
        "woefully",
        "wonderfully",
        "worriedly",
        "wrongly",
        "yawningly",
        "yearly",
        "yearningly",
        "yesterday's",
        "yieldingly",
        "youthfully",
        "zealously",
        "zestfully",
        "zestily",
    ];
    const adjectives = [
        "Anxious",
        "Naughty",
        "Stubborn",
        "Sensitive",
        "Intelligent",
        "Nice",
        "Emotional",
        "Bad-tempered",
        "Nervous",
        "Mean",
        "Distracted",
        "Dishonest",
        "Rude",
        "Discreet",
        "Crazy",
        "Cheeky",
        "Cheerful",
        "Energetic",
        "Untidy",
        "Pessimistic",
        "Optimistic",
        "Unpleasant",
        "Talkative",
        "Calm",
        "Passionate",
        "Proud",
        "Sincere",
        "Lazy",
        "Lively",
        "Funny",
        "Silly",
        "Shy",
        "Determined",
        "Versatile",
        "Sociable",
        "Worried",
        "Thoughtful",
        "Humble",
        "Friendly",
        "Frank",
        "Obedient",
        "Honest",
        "Fearless",
        "Unfriendly",
        "Generous",
        "Compassionate",
        "Warm-hearted",
        "Disobedient",
        "Straightforward",
        "Selfish",
        "Imaginative",
        "Placid",
        "Jealous",
        "Helpful",
        "Enthusiastic",
        "Persistent",
        "Sensible",
        "Rational",
        "Reserved",
        "Self-confident",
        "Bossy",
        "Plucky",
        "Patient",
        "Impatient",
        "Easygoing",
        "Careless",
        "Messy",
        "Hard-working",
        "Creative",
        "Broad-minded",
        "Faithful",
        "Kind",
        "Courageous",
        "Loyal",
        "Modest",
        "Tidy",
        "Confident",
        "Attentive",
        "Loving",
        "Reliable",
        "Scared",
        "Conscientious",
        "Good-tempered",
        "Careful",
        "Gentle",
        "Neat",
        "Dynamic",
        "Fair-minded",
        "Impartial",
        "Supportive",
        "Timid",
        "Intellectual",
        "Brave",
        "Ambitious",
        "Polite",
        "Happy",
        "Romantic",
        "Diplomatic",
        "Courteous",
        "Humorous",
        "Self-disciplined",
        "Popular",
        "Smart",
        "Serious",
        "Hypocritical",
        "Adventurous",
    ];

    const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const adverb = adverbs[Math.floor(Math.random() * adverbs.length)];
    const noun = nouns[Math.floor(Math.random() * nouns.length)];
    const firstWord = Math.round(Math.random()) ? `${adverb} ${adjective.toLowerCase()}` : adjective;
    return `${firstWord.charAt(0).toUpperCase() + firstWord.slice(1)} ${noun.toLowerCase()}`;
};
